version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: database-cargo-sync
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cargo_sync
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cargo-sync-network

  redis:
    image: redis:7
    container_name: cargo-sync-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cargo-sync-network

networks:
  cargo-sync-network:
    driver: bridge

volumes:
  pgdata:
